// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models.EarlyCompletion;

namespace backend.Migrations.EarlyCompletionMigrations
{
    [DbContext(typeof(EarlyCompletionContext))]
    [Migration("20200806151945_EarlyCompletionCreate")]
    partial class EarlyCompletionCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend.Models.EarlyCompletion.EarlyCompletion", b =>
                {
                    b.Property<int>("EarlyCompletionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EarlyCompletionCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EarlyCompletionPhone")
                        .HasColumnType("int");

                    b.Property<string>("OtherInformation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EarlyCompletionId");

                    b.ToTable("EarlyCompletions");
                });
#pragma warning restore 612, 618
        }
    }
}
